# Generated by Django 4.2.2 on 2023-06-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('number_of_employees', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Architector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('company', models.ManyToManyField(to='architectors.company')),
            ],
        ),
    ]
